"""Initial schema

Revision ID: 82b90617ee73
Revises: 
Create Date: 2025-11-10 23:42:24.892100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b90617ee73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severityenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'acknowledged', 'resolved', 'false_positive', name='statusenum'), nullable=False),
    sa.Column('attack_type', sa.String(), nullable=True),
    sa.Column('attack_name', sa.String(), nullable=True),
    sa.Column('correlation_confidence', sa.Float(), nullable=True),
    sa.Column('correlation_summary', sa.String(), nullable=True),
    sa.Column('context_analysis', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_facility_id'), 'alerts', ['facility_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('fl_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'failed', name='roundstatusenum'), nullable=False),
    sa.Column('phase', sa.Enum('distributing', 'training', 'aggregating', 'complete', name='phaseenum'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('epsilon', sa.Float(), nullable=True),
    sa.Column('model_accuracy', sa.Float(), nullable=True),
    sa.Column('clients_active', sa.Integer(), nullable=True),
    sa.Column('total_clients', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fl_rounds_round_number'), 'fl_rounds', ['round_number'], unique=True)
    op.create_table('network_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('packets_per_sec', sa.Integer(), nullable=True),
    sa.Column('bytes_per_sec', sa.Integer(), nullable=True),
    sa.Column('unique_src_ips', sa.Integer(), nullable=True),
    sa.Column('unique_dest_ips', sa.Integer(), nullable=True),
    sa.Column('protocol_distribution', sa.Float(), nullable=True),
    sa.Column('failed_connections', sa.Integer(), nullable=True),
    sa.Column('avg_packet_size', sa.Integer(), nullable=True),
    sa.Column('inter_arrival_time', sa.Integer(), nullable=True),
    sa.Column('raw_features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_data_facility_id'), 'network_data', ['facility_id'], unique=False)
    op.create_index(op.f('ix_network_data_timestamp'), 'network_data', ['timestamp'], unique=False)
    op.create_table('alert_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detection_time', sa.DateTime(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('context_evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fl_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'delayed', 'offline', name='clientstatusenum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_epoch', sa.Integer(), nullable=True),
    sa.Column('total_epochs', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['fl_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('current_technique', sa.String(), nullable=False),
    sa.Column('current_technique_name', sa.String(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('predicted_techniques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.Column('technique_name', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predicted_techniques')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('fl_clients')
    op.drop_table('alert_sources')
    op.drop_index(op.f('ix_network_data_timestamp'), table_name='network_data')
    op.drop_index(op.f('ix_network_data_facility_id'), table_name='network_data')
    op.drop_table('network_data')
    op.drop_index(op.f('ix_fl_rounds_round_number'), table_name='fl_rounds')
    op.drop_table('fl_rounds')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_facility_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
